
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain kitchen)
    (:requirements :equality :typing)
    (:types
        gripper - object
        table - object
        tabletop-object - object
        lid - tabletop-object
        bread - tabletop-object
        pot - tabletop-object
        on-off-object - tabletop-object
        switch - on-off-object
        stove - on-off-object
        object
    )

    (:constants
        
    )

    (:predicates
        (pickupable ?x1 - tabletop-object)
        (directly-on-table ?x1 - tabletop-object ?x2 - table)
        (ontop ?x1 - tabletop-object ?x2 - tabletop-object)
        (in ?x1 - tabletop-object ?x2 - pot)
        (covered ?x1 - pot)
        (on ?x1 - on-off-object)
        (exclusively-occupying-gripper ?x1 - tabletop-object ?x2 - gripper)
        (free ?x1 - gripper)
    )

    (:functions
        
    )

    

    
    (:action pick-up-from-tabletop
     :parameters (?obj - tabletop-object ?table - table ?gripper - gripper)
     :precondition (and (directly-on-table ?obj ?table) (pickupable ?obj) (free ?gripper))
     :effect (and
        (exclusively-occupying-gripper ?obj ?gripper)
        (not (free ?gripper))
        (not (directly-on-table ?obj ?table)))
    )


    (:action place-on-table
     :parameters (?obj - tabletop-object ?table - table ?gripper - gripper)
     :precondition (and (exclusively-occupying-gripper ?obj ?gripper) (not (directly-on-table ?obj ?table)) (pickupable ?obj) (not (free ?gripper)))
     :effect (and
        (directly-on-table ?obj ?table)
        (not (exclusively-occupying-gripper ?obj ?gripper))
        (free ?gripper))
    )


    (:action place-in-pot
     :parameters (?bread - bread ?pot - pot ?gripper - gripper)
     :precondition (and (not (covered ?pot)) (exclusively-occupying-gripper ?bread ?gripper) (not (in ?bread ?pot)) (pickupable ?bread) (not (free ?gripper)))
     :effect (and
        (in ?bread ?pot)
        (not (exclusively-occupying-gripper ?bread ?gripper))
        (free ?gripper))
    )


    (:action place-on-object
     :parameters (?obj1 - tabletop-object ?obj2 - tabletop-object ?gripper - gripper)
     :precondition (and (exclusively-occupying-gripper ?obj1 ?gripper) (pickupable ?obj1) (not (ontop ?obj1 ?obj2)) (not (ontop ?obj2 ?obj1)) (not (free ?gripper)) (not (exclusively-occupying-gripper ?obj2 ?gripper)))
     :effect (and
        (ontop ?obj1 ?obj2)
        (not (exclusively-occupying-gripper ?obj1 ?gripper))
        (free ?gripper))
    )


    (:action turn-on-stove
     :parameters (?switch - switch ?stove - stove ?gripper - gripper)
     :precondition (and (not (on ?stove)) (not (on ?switch)) (free ?gripper))
     :effect (and
        (on ?stove)
        (on ?switch)
        (exclusively-occupying-gripper ?switch ?gripper)
        (not (free ?gripper)))
    )


    (:action free-gripper-from-fixed-object
     :parameters (?obj - tabletop-object ?gripper - gripper)
     :precondition (and (exclusively-occupying-gripper ?obj ?gripper) (not (pickupable ?obj)) (not (free ?gripper)))
     :effect (and
        (not (exclusively-occupying-gripper ?obj ?gripper))
        (free ?gripper))
    )


    (:action pick-up-from-object
     :parameters (?gripper - gripper ?lid - lid ?pot - pot)
     :precondition (and (covered ?pot) (free ?gripper) (not (exclusively-occupying-gripper ?lid ?gripper)) (not (exclusively-occupying-gripper ?pot ?gripper)) (not (in ?lid ?pot)) (not (ontop ?pot ?lid)) (ontop ?lid ?pot) (pickupable ?lid) (pickupable ?pot))
     :effect (and
        (exclusively-occupying-gripper ?lid ?gripper)
        (not (free ?gripper))
        (not (ontop ?lid ?pot))
        (not (covered ?pot)))
    )

)