import copy
import time
import dill
import os
import detection.detector
import execution.executor
import gymnasium as gym
import importlib
import numpy as np
import csv
import stable_baselines3
import logging
import argparse
from tarski import fstrips as fs
from robosuite.wrappers import GymWrapper
from gymnasium.wrappers.time_limit import TimeLimit
from stable_baselines3 import SAC, PPO, DDPG
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import sync_envs_normalization
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.noise import OrnsteinUhlenbeckActionNoise
from typing import *
from learning.reward_functions.rewardFunctionPrompts import *
from learning.custom_callback import *
from learning.custom_gym_wrapper import *
from learning.learning_utils import *
from utils import *
from VLM.openai_api import chat_completion
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="gymnasium")

class LLMRewardShapingFnCandidate:
    """This candidate stores info about the RL candidate trained with reward functions generated by the LLM
    """
    def __init__(self, config, args, domain:str, grounded_op:fs.Action, curr_subgoal:fs.SingleEffect, rw_fn_i:int, save_path:Union[str, os.PathLike]=None):
        self.config = config
        self.domain = domain
        self.args = args
        self.grounded_op = grounded_op
        self.curr_subgoal = curr_subgoal
        self.rw_fn_i = rw_fn_i
        self.subgoal_rw_fn_mapping = None
        self.env = None
        self.eval_env = None
        self.model = None
        self.callbacks = None
        self.eval_callback = None
        self.set_curr_goal_reward_shaping_fn()
        
        # set the paths
        if save_path is not None:
            self.set_save_path(save_path)
            # make the dir if it does not exist
            if not os.path.exists(self.rw_fn_path):
                os.makedirs(self.rw_fn_path)
    
    def get_best_subgoal_in_focus_success_rate(self):
        assert self.eval_callback is not None
        return self.eval_callback.get_best_subgoal_in_focus_success_rate()
    
    def set_model(self, model):
        self.model = model
    
    def learn(self, algo, timesteps, elimination_round=1):
        # if a half trained recent model .zip already exists at the recent_model_path, we should just load it and continue training
        assert self.callbacks is not None
        if os.path.exists(f"{self.recent_model_path}{os.sep}recent_model.zip"):
            model = algo.load(path=f"{self.recent_model_path}{os.sep}recent_model.zip", env=self.env)
            # if the model is off-policy, we need to load the buffer. Check whether the model has the load_replay_buffer method
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{self.recent_model_buffer_path}") and self.args.replay_buffer:
                model.load_replay_buffer(self.recent_model_buffer_path)
            self.set_model(model)
            print(f"Loaded the model from {self.recent_model_path}{os.sep}recent_model.zip")
            # train the model
            if self.args.lr_schedule:
                original_lr = self.config['learning'][self.args.rl_algorithm]['learning_rate']
                curr_iter_timesteps = min(self.args.total_timesteps - self.model.num_timesteps, timesteps*elimination_round - self.model.num_timesteps)
                max_timesteps = self.args.total_timesteps
                self.model.lr_schedule = linear_schedule(original_lr, curr_iter_timesteps, max_timesteps)

            self.model.learn(
                total_timesteps= min(self.args.total_timesteps - self.model.num_timesteps, timesteps*elimination_round - self.model.num_timesteps),
                callback=self.callbacks,
                reset_num_timesteps=False
            )
        else:
            # train the model
            if self.args.lr_schedule:
                original_lr = self.config['learning'][self.args.rl_algorithm]['learning_rate']
                curr_iter_timesteps = timesteps
                max_timesteps = self.args.total_timesteps
                self.model.lr_schedule = linear_schedule(original_lr, curr_iter_timesteps, max_timesteps)
            self.model.learn(
                total_timesteps= timesteps,
                callback=self.callbacks,
                reset_num_timesteps=True
            )
        self.model.save(path=self.final_model_path)
        # if the model is off-policy, we need to save the buffer. Check whether the model has the save_replay_buffer method
        if hasattr(self.model, 'save_replay_buffer'):
            self.model.save_replay_buffer(self.final_model_buffer_path)
    
    def set_env(self, env:Monitor):
        self.env = env
    
    def set_eval_env(self, eval_env:Monitor):
        self.eval_env = eval_env
    
    def set_early_stopping(self, early_stopping:bool):
        if self.eval_callback is not None:
            self.eval_callback.early_stopping = early_stopping
        if self.callbacks is not None:
            for callback in self.callbacks:
                if hasattr(callback, 'early_stopping'):
                    callback.early_stopping = early_stopping
    
    def set_eval_callback(self, eval_callback:EvalCallback):
        self.eval_callback:SubgoalSuccessEvalCallback = eval_callback
    
    def get_last_eval_timesteps(self):
        if self.eval_callback is not None:
            if len(self.eval_callback.evaluations_timesteps) == 0:
                return 0
            return self.eval_callback.evaluations_timesteps[-1]
        else:
            raise ValueError("Eval callback is not set. Cannot get last eval timesteps.")
    
    def set_callbacks(self, callbacks):
        self.callbacks = callbacks   
    
    def set_curr_goal_reward_shaping_fn(self):
        op_name, _ = extract_name_params_from_grounded(self.grounded_op.ident())
        if self.subgoal_rw_fn_mapping is not None:
            self.subgoal_rw_fn_mapping[self.curr_subgoal.pddl_repr()] = load_llm_reward_shaping_fn_candidate(self.domain, op_name, self.rw_fn_i, self.args.rw_type)
        else:
            self.subgoal_rw_fn_mapping = {self.curr_subgoal.pddl_repr(): load_llm_reward_shaping_fn_candidate(self.domain, op_name, self.rw_fn_i, self.args.rw_type)}
        if self.env is not None:
            self.env.env.set_subgoal_reward_shaping_fn(self.curr_subgoal, self.subgoal_rw_fn_mapping[self.curr_subgoal.pddl_repr()])
        if self.eval_env is not None:
            self.eval_env.env.set_subgoal_reward_shaping_fn(self.curr_subgoal, self.subgoal_rw_fn_mapping[self.curr_subgoal.pddl_repr()])
        if self.eval_callback is not None:
            self.eval_callback.eval_env = self.eval_env

    
    def set_save_path(self, save_path:Union[str, os.PathLike]):
        subgoal_name = self.curr_subgoal.pddl_repr().replace(' ', '_')
        self.subgoal_save_path = f"{save_path}{os.sep}{subgoal_name}"
        self.rw_fn_path = f"{self.subgoal_save_path}{os.sep}reward_fn_{self.rw_fn_i}"
        self.final_model_path = f"{self.rw_fn_path}{os.sep}final_model"
        self.final_model_buffer_path = f"{self.final_model_path}{os.sep}buffer.pkl"
        self.best_model_path = f"{self.rw_fn_path}{os.sep}best_model"
        self.best_model_buffer_path = f"{self.best_model_path}{os.sep}buffer.pkl"
        self.recent_model_path = f"{self.rw_fn_path}{os.sep}recent_model"
        self.recent_model_buffer_path = f"{self.recent_model_path}{os.sep}buffer.pkl"
        self.train_logs_path = f"{self.rw_fn_path}{os.sep}train_logs"
        self.eval_logs_path = f"{self.rw_fn_path}_eval{os.sep}eval_logs"
        self.train_monitor_save_path = f"{self.rw_fn_path}{os.sep}monitor_logs"
        self.eval_monitor_save_path = f"{self.rw_fn_path}_eval{os.sep}monitor_logs"
        self.tensorboard_logs_path = f"{self.rw_fn_path}{os.sep}tensorboard_logs"
    
    
    def copy_rw_fn_mapping(self, other):
        # deep copy the other's subgoal_rw_fn_mapping
        self.subgoal_rw_fn_mapping = copy.deepcopy(other.subgoal_rw_fn_mapping)
        if self.env is not None:
            self.env.env.subgoal_reward_shaping_fn_mapping = copy.deepcopy(other.subgoal_rw_fn_mapping)
        if self.eval_env is not None:
            self.eval_env.env.subgoal_reward_shaping_fn_mapping = copy.deepcopy(other.subgoal_rw_fn_mapping)
        if self.eval_callback is not None:
            self.eval_callback.eval_env = self.eval_env
        # make sure to set the current goal's reward shaping function
        self.set_curr_goal_reward_shaping_fn()
    

    def early_stopped(self):
        """Check if the candidate has been early stopped
        """
        if self.eval_callback:
            if not self.eval_callback.early_stopping:
                return False
            if self.eval_callback.evaluations_subgoal_in_focus_successes and len(self.eval_callback.evaluations_subgoal_in_focus_successes) > 5:
                stopped, _, _ = self.eval_callback.check_early_stopping()
                return stopped
        return False
    

class CandidateRegistry:
    """This class stores the reward shaping function candidates
    """
    def __init__(self, subgoal:fs.SingleEffect, log_path:os.PathLike=None):
        self.subgoal = subgoal
        if log_path is not None:
            self.log_path = os.path.join(log_path, "candidate_registry")
        self.timesteps:List[int] = [] # the timesteps at which `eliminate` is called
        self.best_candidate_history:List[int] = [] # the history of the best candidate
        self.best_candidate_performance_history:List[float] = [] # the history of the best candidate's performance
        self.worst_candidate_history:List[int] = [] # the history of the worst candidate
        self.worst_candidate_performance_history:List[float] = []
        self.elimination_history:List[int] = [] # the history of the eliminated candidate

        self.active_candidates:Dict[int, LLMRewardShapingFnCandidate] = OrderedDict()
        self.all_candidates:Dict[int, LLMRewardShapingFnCandidate] = OrderedDict()

        self.elimination_round = 1

    
    def get_train_candidate(self):
        # get the next candidate to be trained
        if len(self.active_candidates) == 0:
            return None
        # if there's an active candidate whose model is trained for a number of timesteps that is not a multiple of the timesteps per iteration, return that candidate
        for i, candidate in self.active_candidates.items():
            if candidate.model is not None and candidate.model.num_timesteps % candidate.args.timesteps_per_iter != 0:
                return candidate
        # if all candidates are trained for a number of timesteps that is a multiple of the timesteps per iteration, return the candidate with the least number of timesteps
        least_trained_candidate = min(self.active_candidates.items(), key=lambda x: x[1].model.num_timesteps)
        return least_trained_candidate[1]
    
    def recover_candidates(self):
        # recover the history from the log file. Assumes that candidates have all been added to all_candidates and active_candidates
        if self.log_path is not None and os.path.exists(f"{self.log_path}.npz"):
            data = np.load(f"{self.log_path}.npz", allow_pickle=True)
            self.timesteps = data['timesteps'].tolist()
            self.best_candidate_history = data['best_candidate'].tolist()
            self.best_candidate_performance_history = data['best_candidate_performance'].tolist()
            self.worst_candidate_history = data['worst_candidate'].tolist()
            self.worst_candidate_performance_history = data['worst_candidate_performance'].tolist()
            self.elimination_history = data['eliminated'].tolist()
            self.elimination_round = data['elimination_round'].item()
            # drop the eliminated candidates from the active_candidates
            for i, eliminated in enumerate(self.elimination_history):
                if eliminated is not None:
                    self.active_candidates.pop(eliminated)

        if self.log_path is not None:
            np.savez(self.log_path, timesteps=self.timesteps, best_candidate=self.best_candidate_history, best_candidate_performance=self.best_candidate_performance_history, worst_candidate=self.worst_candidate_history, worst_candidate_performance=self.worst_candidate_performance_history, eliminated=self.elimination_history, elimination_round=self.elimination_round)
    
    def eliminate(self):

        performances = []
        eliminated = None
        for i, candidate in self.active_candidates.items():
            performance = candidate.eval_callback.get_recent_ave_subgoal_success_rate()
            performances.append((i, performance))
        worst_candidate = min(performances, key=lambda x: x[1])
        # get the best candidate that's not the same as the worst candidate
        best_candidate = max(performances, key=lambda x: x[1] if x[0] != worst_candidate[0] else float("-inf"))
        # make sure a record is not added twice and all models are trained the same amount
        assert self.active_candidates[best_candidate[0]].get_last_eval_timesteps() == self.active_candidates[worst_candidate[0]].get_last_eval_timesteps()
        if len(self.timesteps) > 0 and self.active_candidates[worst_candidate[0]].model.num_timesteps ==  self.timesteps[-1]:
            # if the worst candidate has already been trained for the same number of timesteps, we don't need to eliminate it
            self.elimination_round += 1
            if self.log_path is not None:
                np.savez(self.log_path, timesteps=self.timesteps, best_candidate=self.best_candidate_history, best_candidate_performance=self.best_candidate_performance_history, worst_candidate=self.worst_candidate_history, worst_candidate_performance=self.worst_candidate_performance_history, eliminated=self.elimination_history, elimination_round=self.elimination_round)
            return None

        self.timesteps.append(self.active_candidates[best_candidate[0]].get_last_eval_timesteps())
        
        if len(self.active_candidates) > 1 and (self.active_candidates[worst_candidate[0]].model.num_timesteps >= self.active_candidates[worst_candidate[0]].args.timesteps_per_iter): # start eliminating if there are more than 1 candidates and the worst candidate has been trained for at least one iteration
            eliminated = self.active_candidates.pop(worst_candidate[0])
            self.elimination_history.append(worst_candidate[0])
        else:
            self.elimination_history.append(None)
        # save the timesteps, the candidate history, the best candidate, and the performances
        self.best_candidate_history.append(best_candidate[0])
        self.best_candidate_performance_history.append(best_candidate[1])
        self.worst_candidate_history.append(worst_candidate[0])
        self.worst_candidate_performance_history.append(worst_candidate[1])

        self.elimination_round += 1
        if self.log_path is not None:
            np.savez(self.log_path, timesteps=self.timesteps, best_candidate=self.best_candidate_history, best_candidate_performance=self.best_candidate_performance_history, worst_candidate=self.worst_candidate_history, worst_candidate_performance=self.worst_candidate_performance_history, eliminated=self.elimination_history, elimination_round=self.elimination_round)
        return eliminated

    def add(self, i:int, candidate:LLMRewardShapingFnCandidate):
        # make sure the candidate's subgoal is the same as the registry's subgoal
        if candidate.curr_subgoal.atom.pddl_repr() != self.subgoal.atom.pddl_repr():
            raise ValueError(f"Subgoal of the candidate {candidate.curr_subgoal} does not match the subgoal of the registry {self.subgoal}")
        self.all_candidates[i] = candidate
        self.active_candidates[i] = candidate
    
    def get_least_trained_candidate_timesteps(self):
        least_trained_timesteps = float("inf")
        for candidate in self.active_candidates.values():
            if candidate.model is not None:
                least_trained_timesteps = min(least_trained_timesteps, candidate.model.num_timesteps)
        return least_trained_timesteps
    
    def get_least_trained_candidate(self):
        # get the least trained candidate
        least_trained_candidate = min(self.active_candidates.items(), key=lambda x: x[1].model.num_timesteps)
        return least_trained_candidate[1]
    
    
    def get_best_candidate(self):
        # get the best candidate with the best performance
        idx_best_candidate_pair = max(self.active_candidates.items(), key
        =lambda x: x[1].get_best_subgoal_in_focus_success_rate())
        return idx_best_candidate_pair[1]


class OperatorDiscoverer:
    """This class is responsible for discovering the grounded operator"""
    def __init__(self, env:MujocoEnv, args:argparse.Namespace, config:dict):
        self.config = config
        self.args = args
        self.unwrapped_env = env.unwrapped if hasattr(env, 'unwrapped') else env
        np.random.seed(args.seed)
        
        self.rl_algo = importlib.import_module(f"stable_baselines3.{self.args.rl_algorithm.lower()}").__dict__[self.args.rl_algorithm]
        self.__init_savepath()

        # create the logger
        self.logger = logging.getLogger('discoverer')
        self.logger.setLevel(logging.INFO)
        if self.logger.hasHandlers():
            self.logger.handlers.clear()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        # create a file handler. Create the directory if it does not exist
        if not os.path.exists(self.save_path):
            os.makedirs(self.save_path)
        file_handler = logging.FileHandler(f"{self.save_path}{os.sep}discoverer_logs.log")
        file_handler.setFormatter(formatter)
        self.logger.addHandler(file_handler)

    def __init_savepath(self):
        self.save_path = f"learning{os.sep}discover{os.sep}{self.args.domain}{os.sep}{self.args.rl_algorithm}{os.sep}seed_{self.args.seed}"
    

    def discover_operator(self) -> dict:
        """Discover a grounded operator by launching an RL agent to find a plannable state"""
        final_model_path = f"{self.save_path}{os.sep}final_model"
        final_model_buffer_path = f"{final_model_path}{os.sep}buffer.pkl"
        recent_model_path = f"{self.save_path}{os.sep}recent_model"
        recent_model_buffer_path = f"{recent_model_path}{os.sep}buffer.pkl"
        train_logs_path = f"{self.save_path}{os.sep}train_logs"
        train_monitor_save_path = f"{self.save_path}{os.sep}monitor_logs"
        tensorboard_logs_path = f"{self.save_path}{os.sep}tensorboard_logs"

        # configure the model
        model_kwargs = dict(self.config['learning'][self.args.rl_algorithm])  # copy so we can modify
        if self.args.lr_schedule:
            original_lr = config['learning'][self.args.rl_algorithm]['learning_rate']
            curr_iter_timesteps = self.args.total_timesteps
            max_timesteps = self.args.total_timesteps
            model_kwargs['learning'][self.args.rl_algorithm]['learning_rate'] = linear_schedule(original_lr, curr_iter_timesteps, max_timesteps)
        noise_type = model_kwargs.pop("action_noise", None)
        noise_kwargs = model_kwargs.pop("action_noise_kwargs", None)

        # create the eval env
        env = self._wrap_env(deepcopy_env(self.unwrapped_env, self.config['simulation']), save_path=train_monitor_save_path, record_rollouts=False)
        
        callbacks = []
        if self.args.render_training:
            train_callback = RenderCallback()
            callbacks += [train_callback]
        
        terminate_on_discovery_callback = TerminateOnOperatorDiscoveryCallback(
            op_save_path=self.save_path,
            recent_model_save_path=recent_model_path,
            recent_model_buffer_path=recent_model_buffer_path,
        )
        
        callbacks += [terminate_on_discovery_callback]

        action_noise = None
        if noise_type == "OrnsteinUhlenbeckActionNoise" and noise_kwargs is not None:
            n_actions = self.unwrapped_env.action_space.shape[-1]
            action_noise = OrnsteinUhlenbeckActionNoise(
                mean=np.full(n_actions, noise_kwargs["mean"]),
                sigma=noise_kwargs["sigma"] * np.ones(n_actions),
                theta=noise_kwargs["theta"],
                dt=noise_kwargs["dt"],
        )
        if action_noise == None:
            model = self.rl_algo(
                "MlpPolicy",    
                env = env,
                tensorboard_log=tensorboard_logs_path,
                **model_kwargs
            )
        else:
            model = self.rl_algo(
                "MlpPolicy",    
                env = env,
                tensorboard_log=tensorboard_logs_path,
                action_noise=action_noise,
                **model_kwargs
            )
        
        # check if there's a partially trained model, if so, load it and continue training
        if os.path.exists(f"{recent_model_path}{os.sep}recent_model.zip"):
            model = self.rl_algo.load(path=f"{recent_model_path}{os.sep}recent_model.zip", env=env)
            # if the model is off-policy, we need to load the buffer. Check whether the model has the load_replay_buffer method
            print(f"Loaded the model from {recent_model_path}{os.sep}recent_model.zip")
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{recent_model_buffer_path}") and self.args.replay_buffer:
                model.load_replay_buffer(recent_model_buffer_path)
                print(f"Loaded the buffer from {recent_model_buffer_path}")
            model.tensorboard_log = tensorboard_logs_path
        
            # train the model
            model.learn(
                total_timesteps=self.args.total_timesteps - model.num_timesteps,
                callback=callbacks,
                reset_num_timesteps=False
            )
        else:
            # train the model
            model.learn(
                total_timesteps=self.args.total_timesteps,
                callback=callbacks,
                reset_num_timesteps=True
            )
        # save the model
        model.save(path=final_model_path)
        # if the model is off-policy, we need to save the buffer. Check whether the model has the save_replay_buffer method
        if hasattr(model, 'save_replay_buffer'):
            model.save_replay_buffer(final_model_buffer_path)
        return terminate_on_discovery_callback.discovered_operator
        
    
    def _wrap_env(self, env:MujocoEnv, save_path:str, record_rollouts=False) -> gym.Wrapper:
        """Wrap the environment in multiple wrappers.

        Args:
            env (gym environment): the environment to wrap
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the monitor logs
            record_rollouts (bool): whether to record rollouts

        Returns:
            gym.Wrapper: the wrapped environment
        """
        env = GymWrapper(env)               
        env = TimeLimit(env, max_episode_steps=self.args.ep_len)
        env = OperatorDiscoveryWrapper(
            env=env,
            config = self.config,
            args = self.args,
            save_path=save_path,
        )
        env = Monitor(
            env=env, 
            filename=f"{save_path}{os.sep}monitor_logs",
            allow_early_resets=True,
            info_keywords=('ep_cumu_r_shaping', 'num_symbol_changes', 'discovered_operator', 'changed_symbols')
        )
        return env

class BaseLearner:
    """Learner class that learns the grounded operator using an RL algorithm without the LLM. One learner is associated with one grounded operator. The learner trains an RL agent to learn the entire grounded operator at once. There is no subgoal curriculum learning involved.
    """
    def __init__(self, env:MujocoEnv, args:argparse.Namespace, grounded_operator:fs.Action, config:dict):
        self.config = config
        self.args = args
        # from stable_baselines3 import the learning algorithm
        self.rl_algo = importlib.import_module(f"stable_baselines3.{self.args.rl_algorithm.lower()}").__dict__[self.args.rl_algorithm]
        self.grounded_operator = grounded_operator
        self.unwrapped_env = env.unwrapped if hasattr(env, 'unwrapped') else env
        np.random.seed(args.seed)

        self._init_savepath()
        # create the logger
        # set up a logger here to log the terminal printouts for the training of each subgoal
        self.logger = logging.getLogger('learning')
        self.logger.setLevel(logging.INFO)
        if self.logger.hasHandlers(): # Remove duplicate handlers
            self.logger.handlers.clear()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        # create a file handler. Create the directory if it does not exist
        if not os.path.exists(self.save_path):
            os.makedirs(self.save_path)
        file_handler = logging.FileHandler(f"{self.save_path}{os.sep}learner_train_logs.log")
        file_handler.setFormatter(formatter)
        self.logger.addHandler(file_handler)

    def _init_savepath(self):
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
        self.save_path = f"learning{os.sep}policies{os.sep}{self.args.domain}{os.sep}base{os.sep}{op_name}{os.sep}{self.args.rl_algorithm}{os.sep}{self.args.termination_type}{os.sep}seed_{self.args.seed}_{self.args.rw_type}"
        
        

    def learn_operator(self) -> execution.executor.Executor_RL:
        """Train an RL agent to learn the grounded operator

        Returns:
            execution.executor.Executor_RL: an RL executor for the operator
        """
        
        final_model_path = f"{self.save_path}{os.sep}final_model"
        final_model_buffer_path = f"{final_model_path}{os.sep}buffer.pkl"
        best_model_path = f"{self.save_path}{os.sep}best_model"
        best_model_buffer_path = f"{best_model_path}{os.sep}buffer.pkl"
        recent_model_path = f"{self.save_path}{os.sep}recent_model"
        recent_model_buffer_path = f"{recent_model_path}{os.sep}buffer.pkl"
        train_logs_path = f"{self.save_path}{os.sep}train_logs"
        eval_logs_path = f"{self.save_path}_eval{os.sep}eval_logs"
        train_monitor_save_path = f"{self.save_path}{os.sep}monitor_logs"
        eval_monitor_save_path = f"{self.save_path}_eval{os.sep}monitor_logs"
        tensorboard_logs_path = f"{self.save_path}{os.sep}tensorboard_logs"
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
    

        # configure the model
        model_kwargs = dict(self.config['learning'][self.args.rl_algorithm])  # copy so we can modify
        if self.args.lr_schedule:
            original_lr = config['learning'][self.args.rl_algorithm]['learning_rate']
            curr_iter_timesteps = self.args.total_timesteps
            max_timesteps = self.args.total_timesteps
            model_kwargs['learning'][self.args.rl_algorithm]['learning_rate'] = linear_schedule(original_lr, curr_iter_timesteps, max_timesteps)
        noise_type = model_kwargs.pop("action_noise", None)
        noise_kwargs = model_kwargs.pop("action_noise_kwargs", None)

        # create the eval env
        last_subgoal = self.grounded_operator.effects[-1]
        env = self._wrap_env(deepcopy_env(self.unwrapped_env, self.config['simulation']), save_path=train_monitor_save_path, record_rollouts=False)
        eval_env:Monitor = self._wrap_env(deepcopy_env(self.unwrapped_env, self.config['eval_simulation']), save_path=eval_monitor_save_path, record_rollouts=False)
        eval_callback = SubgoalSuccessEvalCallback(
            subgoal_idx=find_subgoal_idx(self.grounded_operator, last_subgoal),
            eval_env=eval_env,
            best_model_save_path=best_model_path,
            best_model_buffer_path=best_model_buffer_path,
            log_path=eval_logs_path,
            **self.config['learning']['eval'],
            logger=self.logger,
            recent_model_save_path=recent_model_path,
            recent_model_buffer_path=recent_model_buffer_path,
            early_stopping=True
            )
        callbacks = []
        if self.args.render_training:
            train_callback = RenderCallback()
            callbacks += [train_callback]
        
        callbacks += [eval_callback]

        action_noise = None
        if noise_type == "OrnsteinUhlenbeckActionNoise" and noise_kwargs is not None:
            n_actions = self.unwrapped_env.action_space.shape[-1]
            action_noise = OrnsteinUhlenbeckActionNoise(
                mean=np.full(n_actions, noise_kwargs["mean"]),
                sigma=noise_kwargs["sigma"] * np.ones(n_actions),
                theta=noise_kwargs["theta"],
                dt=noise_kwargs["dt"],
        )
        if action_noise == None:
            model = self.rl_algo(
                "MlpPolicy",    
                env = env,
                tensorboard_log=tensorboard_logs_path,
                **model_kwargs
            )
        else:
            model = self.rl_algo(
                "MlpPolicy",    
                env = env,
                tensorboard_log=tensorboard_logs_path,
                action_noise=action_noise,
                **model_kwargs
            )
        
        # check if there's a partially trained model, if so, load it and continue training
        if os.path.exists(f"{recent_model_path}{os.sep}recent_model.zip"):
            model = self.rl_algo.load(path=f"{recent_model_path}{os.sep}recent_model.zip", env=env)
            # if the model is off-policy, we need to load the buffer. Check whether the model has the load_replay_buffer method
            print(f"Loaded the model from {recent_model_path}{os.sep}recent_model.zip")
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{recent_model_buffer_path}") and self.args.replay_buffer:
                model.load_replay_buffer(recent_model_buffer_path)
                print(f"Loaded the buffer from {recent_model_buffer_path}")
            model.tensorboard_log = tensorboard_logs_path
        
            # train the model
            model.learn(
                total_timesteps=self.args.total_timesteps - model.num_timesteps,
                callback=callbacks,
                reset_num_timesteps=False
            )
        else:
            # train the model
            model.learn(
                total_timesteps=self.args.total_timesteps,
                callback=callbacks,
                reset_num_timesteps=True
            )
        # save the model
        model.save(path=final_model_path)
        # if the model is off-policy, we need to save the buffer. Check whether the model has the save_replay_buffer method
        if hasattr(model, 'save_replay_buffer'):
            model.save_replay_buffer(final_model_buffer_path)
        # create an Executor_RL object associated with the newly learned policy.
        executor = execution.executor.Executor_RL(
            operator_name=op_name,
            alg=self.args.rl_algorithm,
            policy=best_model_path
        )
        # Pickle the Executor_RL object and save it to a file. Return the Executor_RL object
        # create if the directory does not exist
        with open(f"{self.save_path}{os.sep}executor.pkl", 'wb') as f:
            dill.dump(executor, f)
        return executor

    def _wrap_env(self, env:MujocoEnv, save_path:str, record_rollouts=False) -> gym.Wrapper:
        """Wrap the environment in multiple wrappers.

        Args:
            env (gym environment): the environment to wrap
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the monitor logs
            record_rollouts (bool): whether to record rollouts

        Returns:
            gym.Wrapper: the wrapped environment
        """
        filtered_obs = filter_observation(get_observation_with_semantics(self.unwrapped_env), self.grounded_operator)
        env = GymWrapper(env, keys=list(filtered_obs.keys()))               
        env = TimeLimit(env, max_episode_steps=self.args.ep_len)
        env = BaseOperatorWrapper(
            env=env,
            config = self.config,
            args = self.args,
            grounded_operator=self.grounded_operator, 
            record_rollouts=record_rollouts,
        )
        subgoals_keys = [f'{eff.pddl_repr()}_subgoal' for eff in remove_duplicate_effects(self.grounded_operator)]
        subgoals_keys += [f'{eff.pddl_repr()}_historical_subgoal' for eff in remove_duplicate_effects(self.grounded_operator)] 
        env = Monitor(
            env=env, 
            filename=f"{save_path}{os.sep}monitor_logs",
            allow_early_resets=True,
            info_keywords=('subgoal_success', 'num_subgoal_in_focus_success_steps', 'historical_subgoal_successes', 'goal_success', 'ep_cumu_r_shaping') + tuple(subgoals_keys)
        )
        return env
    
    
class SubgoalCurriculumLearner(BaseLearner):
    """Learner class that learns the grounded operator using an RL algorithm with a subgoal curriculum. One learner is associated with one grounded operator. The learner trains an RL agent to learn the grounded operator by training the agent to learn each subgoal of the operator in sequence. The learner trains the agent to learn the subgoals in the order they appear in the operator's effects list. 
    """
    def __init__(self, env:MujocoEnv, args:argparse.Namespace, grounded_operator_to_learn:fs.Action, config:dict):
        super().__init__(env, args, grounded_operator_to_learn, config)
        
    def _init_savepath(self):
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
        self.save_path = f"learning{os.sep}policies{os.sep}{self.args.domain}{os.sep}subgoal{os.sep}{op_name}{os.sep}{self.args.rl_algorithm}{os.sep}{self.args.termination_type}{os.sep}seed_{self.args.seed}_{self.args.rw_type}"

    def learn_operator(self) -> execution.executor.Executor_RL:
        """Train an RL agent to learn the grounded operator

        Returns:
            execution.executor.Executor_RL: an RL executor for the operator
        """
        final_operator_model_path = f"{self.save_path}{os.sep}final_model"
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
        
        duplicate_grasp_effects = check_duplicate_grasp_effects(self.grounded_operator)
        duplicate_free_gripper_effects = check_duplicate_free_gripper_effects(self.grounded_operator)
        best_model_path = None
        for effect in self.grounded_operator.effects:
            if effect.pddl_repr() == 'not (free gripper1)' and duplicate_grasp_effects:
                continue
            elif effect.pddl_repr() == 'free gripper1' and duplicate_free_gripper_effects:
                continue
            best_model_path = self.learn_subgoal(effect, self.save_path, prev_subgoal_model_path=best_model_path)
        
        # load the trained model and re-save it to the final operator path for the entire operator
        model = self.rl_algo.load(path=f"{best_model_path}{os.sep}best_model.zip")
        model.save(path=final_operator_model_path)
        # create an Executor_RL object associated with the newly learned policy.
        executor = execution.executor.Executor_RL(
            operator_name=op_name,
            alg=self.args.rl_algorithm,
            policy=final_operator_model_path
        )
        # Pickle the Executor_RL object and save it to a file. Return the Executor_RL object
        with open(f"{self.save_path}{os.sep}executor.pkl", 'wb') as f:
            dill.dump(executor, f)
        return executor
    
    def learn_subgoal(self, subgoal:fs.SingleEffect, save_path:str, prev_subgoal_model_path:Union[str, os.PathLike]=None) -> Union[str, os.PathLike]:
        """Train an RL agent to learn a subgoal/effect of the operator.
        Args:
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the model
            prev_subgoal_model_path (str|os.PathLike): the path to the previous subgoal model
        Returns:
            Tuple[Union[str, os.PathLike], Any]: the path to the model, the trained model
        """
        subgoal_name:str = subgoal.pddl_repr().replace(' ', '_')
        subgoal_save_path = f"{save_path}{os.sep}{subgoal_name}"
        final_model_path = f"{subgoal_save_path}{os.sep}final_model"
        final_model_buffer_path = f"{final_model_path}{os.sep}buffer.pkl"
        best_model_path = f"{subgoal_save_path}{os.sep}best_model"
        best_model_buffer_path = f"{best_model_path}{os.sep}buffer.pkl"
        recent_model_path = f"{subgoal_save_path}{os.sep}recent_model"
        recent_model_buffer_path = f"{recent_model_path}{os.sep}buffer.pkl"
        train_logs_path = f"{subgoal_save_path}{os.sep}train_logs"
        eval_logs_path = f"{subgoal_save_path}_eval{os.sep}eval_logs"
        train_monitor_save_path = f"{subgoal_save_path}{os.sep}monitor_logs"
        eval_monitor_save_path = f"{subgoal_save_path}_eval{os.sep}monitor_logs"
        tensorboard_logs_path = f"{subgoal_save_path}{os.sep}tensorboard_logs"

        if not os.path.exists(subgoal_save_path):
            os.makedirs(subgoal_save_path)
        # Remove duplicate handlers
        if self.logger.hasHandlers():
            self.logger.handlers.clear()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        file_handler = logging.FileHandler(train_logs_path)
        file_handler.setFormatter(formatter)
        self.logger.addHandler(file_handler)

        # initialize training env
        env:Monitor = self._wrap_env(self.unwrapped_env, subgoal=subgoal, save_path=train_monitor_save_path)  
        # initialize the evaluation environment
        eval_env:Monitor = self._wrap_env(deepcopy_env(self.unwrapped_env, self.config['eval_simulation']), subgoal=subgoal, save_path=eval_monitor_save_path, record_rollouts=False)
        # initialize the evalcallback
        eval_callback = SubgoalSuccessEvalCallback(
            subgoal_idx=find_subgoal_idx(self.grounded_operator, subgoal),
            eval_env=eval_env,
            best_model_save_path=best_model_path,
            best_model_buffer_path=best_model_buffer_path,
            log_path=eval_logs_path,
            **self.config['learning']['eval'],
            logger=self.logger,
            recent_model_save_path=recent_model_path,
            recent_model_buffer_path=recent_model_buffer_path,
            early_stopping=True
        )

        callbacks = []
        if self.args.render_training:
            train_callback = RenderCallback()
            callbacks += [train_callback]
        
        callbacks += [eval_callback]
        
        if self.args.lr_schedule:
            original_lr = config['learning'][self.args.rl_algorithm]['learning_rate']
            curr_iter_timesteps = self.args.total_timesteps
            max_timesteps = self.args.total_timesteps
            self.config['learning'][self.args.rl_algorithm]['learning_rate'] = linear_schedule(original_lr, curr_iter_timesteps, max_timesteps)
        

        # if the model has been trained before, load the model and the environment to continue training
        if prev_subgoal_model_path is not None:
            model = self.rl_algo.load(path=f"{prev_subgoal_model_path}{os.sep}best_model.zip", env=env)
            # if the model is off-policy, we need to load the buffer. Check whether the model has the load_replay_buffer method
            print(f"Loaded the model from {prev_subgoal_model_path}{os.sep}best_model.zip")
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{prev_subgoal_model_path}{os.sep}buffer.pkl") and self.args.replay_buffer:
                model.load_replay_buffer(f"{prev_subgoal_model_path}{os.sep}buffer.pkl")
                print(f"Loaded the buffer from {prev_subgoal_model_path}{os.sep}buffer.pkl")
            model.tensorboard_log = tensorboard_logs_path
        else: # if the model has not been trained before, initialize the model and the environment
            model = self.rl_algo(
                "MlpPolicy",    
                env = env,
                tensorboard_log=tensorboard_logs_path,
                **self.config['learning'][self.args.rl_algorithm]
            )
        # if a half trained recent model .zip already exists at the recent_model_path, we should just load it and continue training
        if os.path.exists(f"{recent_model_path}{os.sep}recent_model.zip"):
            model = self.rl_algo.load(path=f"{recent_model_path}{os.sep}recent_model.zip", env=env)
            # if the model is off-policy, we need to load the buffer. Check whether the model has the load_replay_buffer method
            print(f"Loaded the model from {recent_model_path}{os.sep}recent_model.zip")
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{recent_model_buffer_path}") and self.args.replay_buffer:
                model.load_replay_buffer(recent_model_buffer_path)
                print(f"Loaded the buffer from {recent_model_buffer_path}")

            stopped = False
            if eval_callback.evaluations_subgoal_in_focus_successes and len(eval_callback.evaluations_subgoal_in_focus_successes) > 5:
                stopped, _, _ = eval_callback.check_early_stopping()
            if stopped:
                print("Early stopping is enabled and the model has been early stopped.")
                # save the model
                model.save(path=final_model_path)
                # if the model is off-policy, we need to save the buffer. Check whether the model has the save_replay_buffer method
                if hasattr(model, 'save_replay_buffer'):
                    model.save_replay_buffer(final_model_buffer_path)
                return best_model_path
            
            model.learn(
                total_timesteps=self.args.total_timesteps - model.num_timesteps,
                callback=callbacks,
                reset_num_timesteps=False
            )
        else:
            # train the model
            model.learn(
                total_timesteps=self.args.total_timesteps,
                callback=callbacks,
                reset_num_timesteps=True
            )
        # save the model
        model.save(path=final_model_path)
        # if the model is off-policy, we need to save the buffer. Check whether the model has the save_replay_buffer method
        if hasattr(model, 'save_replay_buffer'):
            model.save_replay_buffer(final_model_buffer_path)
        return best_model_path
        
    def _wrap_env(self, env:MujocoEnv, subgoal:fs.SingleEffect, save_path:str, record_rollouts=False) -> gym.Wrapper:
        """Wrap the environment in multiple wrappers.

        Args:
            env (gym environment): the environment to wrap
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the monitor logs
            record_rollouts (bool): whether to record rollouts

        Returns:
            gym.Wrapper: the wrapped environment
        """
        filtered_obs = filter_observation(get_observation_with_semantics(self.unwrapped_env), self.grounded_operator)
        env = GymWrapper(env, keys=list(filtered_obs.keys()))
        subgoal_idx = find_subgoal_idx(self.grounded_operator, subgoal)
        if self.args.termination_type=='on_all_subgoal_success':                 
            env = TimeLimit(env, max_episode_steps=self.args.ep_len * (subgoal_idx + 1))
        else:
            env = TimeLimit(env, max_episode_steps=0.5 * self.args.ep_len * (subgoal_idx + 2))
        env = CollisionLLMAblatedOperatorWrapper(
            env=env,
            config = self.config,
            args = self.args,
            grounded_operator=self.grounded_operator, 
            curr_subgoal=subgoal, 
            record_rollouts=record_rollouts,
        )
        subgoals_keys = [f'{eff.pddl_repr()}_subgoal' for eff in remove_duplicate_effects(self.grounded_operator)]
        subgoals_keys += [f'{eff.pddl_repr()}_historical_subgoal' for eff in remove_duplicate_effects(self.grounded_operator)] 
        env = Monitor(
            env=env, 
            filename=f"{save_path}{os.sep}monitor_logs",
            allow_early_resets=True,
            info_keywords=('subgoal_success', 'num_subgoal_in_focus_success_steps', 'historical_subgoal_successes', 'goal_success', 'ep_cumu_r_shaping') + tuple(subgoals_keys)
        )
        return env

class LLMSubgoalCurriculumLearner(SubgoalCurriculumLearner):
    """prompts the LLM for reward shaping function candidates for the grounded operator and learns the grounded operator using the reward shaping function candidates
    """
    def __init__(self, env:MujocoEnv, args:argparse.Namespace, grounded_operator_to_learn:fs.Action, config:dict):
        super().__init__(env, args, grounded_operator_to_learn, config)
        self.llm_reward_candidates = self._load_llm_reward_fn_candidates()
        self.logger = logging.getLogger('learning')
        self.logger.setLevel(logging.INFO)
        if self.logger.hasHandlers(): # Remove duplicate handlers
            self.logger.handlers.clear()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        # create a file handler. Create the directory if it does not exist
        if not os.path.exists(self.save_path):
            os.makedirs(self.save_path)
        

    def _init_savepath(self):
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
        self.save_path = f"learning{os.sep}policies{os.sep}{self.args.domain}{os.sep}llm_subgoal{os.sep}{op_name}{os.sep}{self.args.rl_algorithm}{os.sep}{self.args.termination_type}{os.sep}seed_{self.args.seed}_{self.args.rw_type}"
        
    
    
    def _load_llm_reward_fn_candidates(self) -> List[Callable]:
        """Load the LLM generated reward shaping function candidates for the grounded operator

        Returns:
            List[Callable]: a list of reward shaping functions
        """
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
        reward_fn_candidates = []
        for i in range(self.config['learning']['reward_shaping_fn']['num_candidates']):
            try:
                llm_reward_shaping_func = load_llm_reward_shaping_fn_candidate(self.args.domain, op_name, i, self.args.rw_type)
                reward_fn_candidates.append(llm_reward_shaping_func)
            except:
                func = prompt_llm_for_reward_shaping_fn_candidate(self.grounded_operator, get_observation_with_semantics(self.unwrapped_env), self.args.rw_type)
                # save the output python function to a file in the reward_functions directory
                # create the directory if it does not exist
                if not os.path.exists(f"learning{os.sep}reward_functions{os.sep}{self.args.domain}"):
                    os.makedirs(f"learning{os.sep}reward_functions{os.sep}{self.args.domain}")
                # create a file with the operator's name and save the function in it
                with open(f"learning{os.sep}reward_functions{os.sep}{self.args.domain}{os.sep}{op_name}_{i}.py", 'w') as f:
                    f.write(func)
                # wait 5 seconds for the file to be saved
                time.sleep(5)
                llm_reward_func_module = importlib.import_module(f"learning.reward_functions.{self.args.domain}.{op_name}_{i}")
                llm_reward_shaping_func = getattr(llm_reward_func_module, 'reward_shaping_fn')
                reward_fn_candidates.append(llm_reward_shaping_func)
        return reward_fn_candidates
    
    def _filter_semantically_same_candidates(self, subgoal:fs.SingleEffect, candidates:List[LLMRewardShapingFnCandidate]) -> Dict[int, LLMRewardShapingFnCandidate]:
        """Filter out reward shaping function candidates that are semantically the same for the current subgoal

        Args:
            subgoal (fs.SingleEffect): the subgoal to check the candidates against
            candidates (List[LLMRewardShapingFnCandidate]): the list of reward shaping function candidates to filter

        Returns:
            Dict[int, LLMRewardShapingFnCandidate]: a dictionary of the filtered reward shaping function candidates, where the keys are the indices of the candidates in the original list and the values are the candidates themselves
        """
        candidate_idxs_to_remove = set()
        # for each pair of candidates, check whether they are semantically the same for the current subgoal. If they are, add the one with the higher index to the candidate_idxs_to_remove set
        for i in range(len(candidates)):
            for j in range(i + 1, len(candidates)):
                if check_subgoal_duplicate(subgoal=subgoal, candidate1=candidates[i], candidate2=candidates[j], env=self.unwrapped_env):
                    candidate_idxs_to_remove.add(j)
        # Remove the filtered candidates from the list
        filtered_candidates = {i: candidate for i, candidate in enumerate(candidates) if i not in candidate_idxs_to_remove}
        return filtered_candidates

    def learn_operator(self) -> execution.executor.Executor_RL:
        """Train an RL agent to learn the grounded operator

        Returns:
            execution.executor.Executor_RL: an RL executor for the operator
        """
        final_operator_model_path = f"{self.save_path}{os.sep}final_model"
        op_name, _ = extract_name_params_from_grounded(self.grounded_operator.ident())
        
        duplicate_grasp_effects = check_duplicate_grasp_effects(self.grounded_operator)
        duplicate_free_gripper_effects = check_duplicate_free_gripper_effects(self.grounded_operator)
        best_candidate = None
        
        for effect in self.grounded_operator.effects:
            if effect.pddl_repr() == 'not (free gripper1)' and duplicate_grasp_effects:
                continue
            elif effect.pddl_repr() == 'free gripper1' and duplicate_free_gripper_effects:
                continue
            best_candidate = self.learn_subgoal(effect, self.save_path, prev_subgoal_candidate=best_candidate)
        
        # load the trained model and re-save it for the entire operator
        model = self.rl_algo.load(path=f"{best_candidate.best_model_path}{os.sep}best_model.zip")
        model.save(path=final_operator_model_path)
        # create an Executor_RL object associated with the newly learned policy.
        executor = execution.executor.Executor_RL(
            operator_name=op_name,
            alg=self.args.rl_algorithm,
            policy=final_operator_model_path
        )
        # Pickle the Executor_RL object and save it to a file. Return the Executor_RL object
        with open(f"{self.save_path}{os.sep}executor.pkl", 'wb') as f:
            dill.dump(executor, f)
        return executor
        
    
    def learn_subgoal(self, subgoal:fs.SingleEffect, save_path:str, prev_subgoal_candidate:LLMRewardShapingFnCandidate=None) -> Tuple[str, Monitor, Any]:
        """Train an RL agent to learn a subgoal/effect of the operator.
        Args:
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the model
            prev_subgoal_candidate (LLMRewardShapingFnCandidate): the previous subgoal candidate data
        Returns:
            Tuple[str, Monitor, CustomEvalCallback]: the path to the model, the environment, and the evaluation callback
        """
        # start log
        # remove duplicate handlers
        if self.logger.hasHandlers():
            self.logger.handlers.clear()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        train_logs_path = f"{save_path}{os.sep}{subgoal.pddl_repr().replace(' ', '_')}"
        if not os.path.exists(train_logs_path):
            os.makedirs(train_logs_path)
        file_handler = logging.FileHandler(f"{train_logs_path}{os.sep}train_logs.log")
        file_handler.setFormatter(formatter)
        self.logger.addHandler(file_handler)
        # train each reward function candidate sequentially for a set number of timesteps, compare their performance, and eliminate the worst performing one.
        # initialize the rw fn candidates
        
        registry = CandidateRegistry(subgoal=subgoal, log_path=train_logs_path)
        # filter out candidates that are semantically the same for this subgoal to avoid training multiple candidates that have the same reward shaping function for this subgoal
        filtered_candidates = self._filter_semantically_same_candidates(subgoal, self.llm_reward_candidates)
        for i, candidate in filtered_candidates.items():
            try:
                print("Creating reward shaping function candidate", i)
                candidate = self.create_subgoal_rw_fn_candidate(subgoal, save_path, rw_fn_i=i,  prev_subgoal_candidate=prev_subgoal_candidate)
            except Exception as e:
                print(e)
                self.logger.error(e)
                continue
            registry.add(i, candidate)
        print(f"active candidates after filtering semantically same ones: {[candidate.rw_fn_i for candidate in registry.active_candidates.values()]}")
        # recover possible training history
        registry.recover_candidates()
        
        while len(registry.active_candidates) > 1: # keep training until there is only one candidate left
            for candidate in registry.active_candidates.values():   
                print("Continue Learning subgoal with reward shaping function candidate", candidate.rw_fn_i)
                candidate.learn(algo=self.rl_algo, timesteps=self.args.timesteps_per_iter, elimination_round=registry.elimination_round)
            eliminated = registry.eliminate()
            if eliminated is not None:
                self.logger.info(f"Eliminated the worst performing candidate {eliminated.rw_fn_i} subgoal {subgoal} after running for {eliminated.model.num_timesteps} with a performance of {eliminated.eval_callback.get_best_subgoal_in_focus_success_rate()}")
        
        last_candidate = registry.get_least_trained_candidate()
        if last_candidate.model.num_timesteps < self.args.total_timesteps:
            # continue training the last candidate
            print("Continue training the last candidate", last_candidate.rw_fn_i)
            last_candidate.set_early_stopping(True) # enable early stopping
            if not last_candidate.early_stopped(): # if the last candidate has not been early stopped, continue training it
                last_candidate.learn(algo=self.rl_algo, timesteps=self.args.total_timesteps - last_candidate.model.num_timesteps, elimination_round=registry.elimination_round)
        
        return registry.get_best_candidate()

    def create_subgoal_rw_fn_candidate(self, subgoal:fs.SingleEffect, save_path:str, rw_fn_i:int, prev_subgoal_candidate:LLMRewardShapingFnCandidate=None) -> LLMRewardShapingFnCandidate:
        """Train an RL agent to learn a subgoal/effect of the operator using a reward shaping function candidate

        Args:
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the model
            rw_fn_i (int): the index of the reward shaping function candidate
            prev_subgoal_candidate (LLMRewardShapingFnCandidate): the previous subgoal candidate data

        Returns:
            LLMRewardShapingFnCandidate: the trained subgoal candidate
        """
        candidate = LLMRewardShapingFnCandidate(
            config=self.config,
            args = self.args,
            domain=self.args.domain,
            grounded_op=self.grounded_operator,
            curr_subgoal=subgoal,
            rw_fn_i=rw_fn_i,
            save_path=save_path
        )
        
        
        logger = logging.getLogger('learning')
        logger.setLevel(logging.INFO)
        # remove duplicate handlers
        if logger.hasHandlers():
            logger.handlers.clear()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        file_handler = logging.FileHandler(candidate.train_logs_path)
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)

        # initialize the training environment
        env:Monitor = self._wrap_env(self.unwrapped_env, subgoal=subgoal, save_path=candidate.train_monitor_save_path)
        # initialize the eval environment
        eval_env:Monitor = self._wrap_env(deepcopy_env(self.unwrapped_env, self.config['eval_simulation']), subgoal=subgoal, save_path=candidate.eval_monitor_save_path, record_rollouts=False)
        # initialize the eval callback
        eval_callback = SubgoalSuccessEvalCallback(
            subgoal_idx=find_subgoal_idx(self.grounded_operator, subgoal),
            eval_env=eval_env,
            best_model_save_path=candidate.best_model_path,
            best_model_buffer_path=candidate.best_model_buffer_path,
            log_path=candidate.eval_logs_path,
            **self.config['learning']['eval'],
            logger=logger,
            recent_model_save_path=candidate.recent_model_path,
            recent_model_buffer_path=candidate.recent_model_buffer_path
        )
        candidate.set_env(env)
        candidate.set_eval_env(eval_env)
        candidate.set_eval_callback(eval_callback)

        if prev_subgoal_candidate is not None:
            candidate.copy_rw_fn_mapping(prev_subgoal_candidate)
        candidate.set_curr_goal_reward_shaping_fn()

        # if the prev subgoal model has been trained before, load the model and the environment to continue training
        if prev_subgoal_candidate is not None:
            model = self.rl_algo.load(path=f"{prev_subgoal_candidate.best_model_path}{os.sep}best_model.zip", env=env)
            print(f"Loaded the model from {prev_subgoal_candidate.best_model_path}{os.sep}best_model.zip")
            # check if the model is off-policy, if so, load the buffer
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{prev_subgoal_candidate.best_model_buffer_path}") and self.args.replay_buffer:
                model.load_replay_buffer(f"{prev_subgoal_candidate.best_model_buffer_path}")
                print(f"Loaded the buffer from {prev_subgoal_candidate.best_model_buffer_path}")
            model.num_timesteps = 0
            model.tensorboard_log = candidate.tensorboard_logs_path
        else: # if no prev subgoal model has been trained before, initialize the model and the environment
            model = self.rl_algo(
                "MlpPolicy",    
                env = env,
                tensorboard_log=candidate.tensorboard_logs_path,
                **self.config['learning'][self.args.rl_algorithm]
            )
        
        # also check if a half trained recent model .zip already exists at the recent_model_path, we should just load it and continue training
        if os.path.exists(f"{candidate.recent_model_path}{os.sep}recent_model.zip"):
            model = self.rl_algo.load(path=f"{candidate.recent_model_path}{os.sep}recent_model.zip", env=env)
            print(f"Loaded the model from {candidate.recent_model_path}{os.sep}recent_model.zip")
            # check if the model is off-policy, if so, load the buffer
            if hasattr(model, 'load_replay_buffer') and os.path.exists(f"{candidate.recent_model_buffer_path}") and self.args.replay_buffer:
                model.load_replay_buffer(f"{candidate.recent_model_buffer_path}")
                print(f"Loaded the buffer from {candidate.recent_model_buffer_path}")
        candidate.set_model(model)

        callbacks = []
        if self.args.render_training:
            train_callback = RenderCallback()
            callbacks += [train_callback]
        
        callbacks += [eval_callback]
        
        candidate.set_callbacks(callbacks)

        return candidate   
    

    def _wrap_env(self, env:MujocoEnv, subgoal:fs.SingleEffect, save_path:str, record_rollouts=False) -> gym.Wrapper:
        """Wrap the environment in multiple wrappers.

        Args:
            env (gym environment): the environment to wrap
            subgoal (fs.SingleEffect): the subgoal to learn
            save_path (str): the path to save the monitor logs
            record_rollouts (bool): whether to record rollouts

        Returns:
            gym.Wrapper: the wrapped environment
        """
        filtered_obs = filter_observation(get_observation_with_semantics(self.unwrapped_env), self.grounded_operator)
        env = GymWrapper(env, keys=list(filtered_obs.keys()))
        subgoal_idx = find_subgoal_idx(self.grounded_operator, subgoal)                 
        if self.args.termination_type=='on_all_subgoal_success':                 
            env = TimeLimit(env, max_episode_steps=self.args.ep_len * (subgoal_idx + 1))
        else:
            env = TimeLimit(env, max_episode_steps=0.5 * self.args.ep_len * (subgoal_idx + 2))
        env = CollisionAblatedOperatorWrapper(
            env=env,
            config = self.config,
            args = self.args,
            grounded_operator=self.grounded_operator, 
            curr_subgoal=subgoal, 
            record_rollouts=record_rollouts,
        )
        subgoals_keys = [f'{eff.pddl_repr()}_subgoal' for eff in remove_duplicate_effects(self.grounded_operator)]
        subgoals_keys += [f'{eff.pddl_repr()}_historical_subgoal' for eff in remove_duplicate_effects(self.grounded_operator)]  
        env = Monitor(
            env=env, 
            filename=f"{save_path}{os.sep}monitor_logs",
            allow_early_resets=True,
            info_keywords=('subgoal_success', 'num_subgoal_in_focus_success_steps', 'historical_subgoal_successes', 'goal_success', 'ep_cumu_r_shaping') + tuple(subgoals_keys)
        )
        return env
