import tarski.fstrips as fs
from execution.executor import Executor
from tarski.syntax.formulas import Connective, Formula
from typing import *
from utils import *
from VLM.openai_api import *
from learning.reward_functions.rewardFunctionPrompts import *
from learning.custom_callback import *



def load_llm_reward_shaping_fn_candidate(domain:str, op_name:str, candidate_idx:int, rw_type:str=None) -> Callable:
    """Load the reward shaping function candidate generated by the LLM

    Args:
        candidate_idx (int): the index of the candidate

    Returns:
        Callable: the reward shaping function
    """
    try:
        if rw_type is not None:
            llm_rw_fn_module = importlib.import_module(f"learning.reward_functions.{domain}.{op_name}_{rw_type}_{candidate_idx}")
        else:
            llm_rw_fn_module = importlib.import_module(f"learning.reward_functions.{domain}.{op_name}_{candidate_idx}")
        llm_reward_shaping_func = getattr(llm_rw_fn_module, 'reward_shaping_fn')
    except ModuleNotFoundError:
        raise ValueError(f"Reward shaping function candidate {candidate_idx} not found")
    return llm_reward_shaping_func


def linear_schedule(initial_value):
    def schedule(progress_remaining):
        """Linear schedule for the learning rate"""
        return initial_value * progress_remaining
    return schedule

def check_condition_satisfied(condition:Union[fs.SingleEffect, Formula, str], binary_obs:dict) -> bool:
    """Check if the condition is satisfied in the binary observation

    Args:
        condition (Union[fs.Action, Formula]): the condition to check
        binary_obs (dict): the binary observation with semantics

    Returns:
        bool: True if the condition is satisfied, False otherwise
    """
    # check if it's effect or precondition
    if isinstance(condition, fs.SingleEffect): # it's an effect
        is_effect_negated = isinstance(condition, fs.DelEffect)
        if is_effect_negated:
            return binary_obs[condition.atom.pddl_repr()] == False
        else:
            return binary_obs[condition.atom.pddl_repr()] == True
    elif isinstance(condition, Formula): # it's a precondition
        is_precon_negated = hasattr(condition, 'connective') and condition.connective == Connective.Not
        condition_name = condition.subformulas[0].pddl_repr() if is_precon_negated else condition.pddl_repr()
        if is_precon_negated:
            return binary_obs[condition_name] == False
        else:
            return binary_obs[condition_name] == True
    else: # it's a string
        is_negated = condition.startswith('not')
        # remove the 'not' if it's present
        condition_name = split_by_parentheses(condition, type='single_condition')[0] if is_negated else condition
        if is_negated:
            return binary_obs[condition_name] == False
        else:
            return binary_obs[condition_name] == True


def check_effect_satisfied(effect:fs.SingleEffect, last_effect:fs.SingleEffect, binary_obs:dict, grounded_operator:fs.Action) -> bool:
    """check if all the effects up to the given effect are satisfied and the remaining preconditions are unchanged in the binary observation. The desired effect state is the precondition + the effect

    Args:
        effect (fs.SingleEffect): the effect to check
        last_effect (fs.SingleEffect): the last effect that's expected to possibly be satisfied. Effects after this effect in the grounded operator's effects are expected to be unsatisfied

    Returns:
        bool: True if the effect is satisfied, False otherwise
    """
    effect_name = effect.atom.pddl_repr()# e.g. `open drawer1``
    last_effect_name = last_effect.atom.pddl_repr() # e.g. `open drawer1`
    duplicate_grasp_effects = check_duplicate_grasp_effects(grounded_operator)
    duplicate_ungrasp_effects = check_duplicate_free_gripper_effects(grounded_operator)
    effects_possibly_satisfied = set()
    effects = remove_duplicate_effects(grounded_operator)
    # check if every effect up to and including the effect is satisfied
    for effect in effects:
        if not check_condition_satisfied(effect, binary_obs):
            return False
        # check if it's the input effect
        if effect.atom.pddl_repr() == effect_name:
            break
    # add effects up to and including the last effect to the effects_possibly_satisfied
    for effect in effects:
        effects_possibly_satisfied.add(effect.atom.pddl_repr())
        if effect.atom.pddl_repr() == last_effect_name:
            break
    # if duplicate grasp effects are present, then make sure both effects are added to the effects to be satisfied and are satisfied
    if duplicate_grasp_effects or duplicate_ungrasp_effects:
        if all(['exlusively-occupying-gripper' in effect_name for effect_name in effects_possibly_satisfied]):
            effects_possibly_satisfied.add('free gripper1') # add if not already present
    if duplicate_ungrasp_effects:
        if 'exclusively-occupying-gripper' in effect_name or 'exclusively-occupying-gripper' in last_effect_name:
            effects_possibly_satisfied.add('free gripper1') # add if not already present
        

    # check if the remaining preconditions are unchanged
    for condition in grounded_operator.precondition.subformulas:
        # skip 'free gripper' if there's duplicate grasp effects and duplicate ungrasp effects
        if condition.pddl_repr() == 'free gripper1' and (duplicate_grasp_effects or duplicate_ungrasp_effects):
            continue
        is_precon_negated = hasattr(condition, 'connective') and condition.connective == Connective.Not
        condition_name = condition.subformulas[0].pddl_repr() if is_precon_negated else condition.pddl_repr()
        # check if condition is overwritten by the any effect to be satisfied
        if condition_name in effects_possibly_satisfied:
            # effects to be satisfied have already been checked
            continue
        else:
            if not check_condition_satisfied(condition, binary_obs):
                return False
    return True

def check_duplicate_grasp_effects(grounded_operator:fs.Action) -> bool:
    """check if the grounded operator has both `not (free gripper1)` and `exclusively-occupying-gripper ?object gripper1` effects. If so, they should count as one effect
    Args:
        grounded_operator (fs.Action): the grounded operator
    Returns:
        bool: True if both effects are present, False otherwise
    """
    effects:List[fs.SingleEffect] = grounded_operator.effects
    # check if `not (free gripper1)` and `exclusively-occupying-gripper ?object gripper1` are both in the effects. If so, they should count as one effect
    not_free_gripper_effect_present = False
    exclusively_occupying_gripper_effect_present = False
    for effect in effects:
        if effect.atom.pddl_repr() == 'free gripper1' and isinstance(effect, fs.DelEffect): # `not (free gripper1)` is present
            not_free_gripper_effect_present = True
        elif effect.atom.predicate.name == 'exclusively-occupying-gripper':
            exclusively_occupying_gripper_effect_present = True
    return not_free_gripper_effect_present and exclusively_occupying_gripper_effect_present

def check_duplicate_free_gripper_effects(grounded_operator:fs.Action) -> bool:
    """check if the grounded operator has both `not (exclusively-occupying-gripper ?object gripper1)` and `free gripper1` effects. If so, they should count as one effect
    Args:
        grounded_operator (fs.Action): the grounded operator
    Returns:
        bool: True if both effects are present, False otherwise
    """
    effects:List[fs.SingleEffect] = grounded_operator.effects
    # check if `not (exclusively-occupying-gripper ?object gripper1)` and `free gripper1` are both in the effects. If so, they should count as one effect
    not_exclusively_occupying_gripper_effect_present = False
    free_gripper_effect_present = False
    for effect in effects:
        if effect.atom.predicate.name == 'exclusively-occupying-gripper' and isinstance(effect, fs.DelEffect): # `not (exclusively-occupying-gripper ?object gripper1)` is present
            not_exclusively_occupying_gripper_effect_present = True
        elif effect.atom.pddl_repr() == 'free gripper1' and isinstance(effect, fs.AddEffect): # `free gripper1` is present
            free_gripper_effect_present = True
    return not_exclusively_occupying_gripper_effect_present and free_gripper_effect_present


def generate_random_obs_with_semantics(env:MujocoEnv) -> Tuple[dict, dict]:
    """Generate a random observation by taking a random action in the environment and getting the observation with semantics. This is used for checking if the reward shaping function candidates are different by generating random observations with semantics and checking the reward shaping for the same observation in different candidates.

    Args:
        env (MujocoEnv): the environment to use for generating observations with semantics

    Returns:
        tuple[dict, dict]: a tuple containing the previous and current observations with semantics
    """
    # Take a random action and get the resulting observation with semantics. Each float in the random action should be in the range of [-0.016, 0.016]
    prev_obs = env.reset()
    # take 10 zero actions for the env to be stabilized
    for _ in range(10):
        zero_action = np.zeros(env.action_dim)
        prev_obs, _, _, _ = env.step(zero_action) 
    # rand_action = np.random.uniform(low=-0.016, high=0.016, size=env.action_dim)
    # curr_obs, _, _, _ = env.step(rand_action)
    # perturb the observation by adding a random noise in the range of [-0.016, 0.016] to each float value in the observation
    curr_obs = {}
    for key, value in prev_obs.items():
        if isinstance(value, (int, float)):
            noise = np.random.uniform(low=-0.016, high=0.016)
            curr_obs[key] = value + noise
        elif isinstance(value, np.ndarray):
            noise = np.random.uniform(low=-0.016, high=0.016, size=value.shape)
            curr_obs[key] = value + noise
        else:
            curr_obs[key] = value
    return prev_obs, curr_obs


def check_subgoal_duplicate(
    subgoal:Union[fs.SingleEffect, str],
    candidate1:callable,
    candidate2:callable,
    env:MujocoEnv,
) -> bool:
    """Check if reward shaping for a given subgoal/effect is duplicate in two candidates.

    Args:
        subgoal (Union[fs.SingleEffect, str]): the subgoal/effect to check
        candidate1 (callable): the first reward function candidate
        candidate2 (callable): the second reward function candidate
        env (MujocoEnv): the environment to use for generating observations with semantics for checking the reward shaping function candidates

    Returns:
        bool: True if the reward shaping for the subgoal/effect is duplicate, else False
    """
    # randomly generate 10 pairs of previous and current observations with semantics and check if the reward shaping for the subgoal is the same for both candidates for all observation
    for _ in range(10):
        prev_obs, curr_obs = generate_random_obs_with_semantics(env)
        grounded_effect_repr = subgoal.pddl_repr() if isinstance(subgoal, fs.SingleEffect) else subgoal
        reward1 = candidate1(prev_obs, curr_obs, f"({grounded_effect_repr})")
        reward2 = candidate2(prev_obs, curr_obs, f"({grounded_effect_repr})")
        # check if rewards are equal up to 10e-5
        if abs(reward1 - reward2) > 1e-5:
            return False
    return True

def check_duplicate_reward_shaping_fn_candidates(candidate1:callable, candidate2:callable, grounded_op:fs.action.PlainOperator, init_obs_with_semantics:dict, rw_type:str='pos_vel') -> Dict[str, bool]:
    """check the subgoal reward shaping in the two candidates for each subgoal/effect and return a dictionary whose values indicate which subgoals are duplicate

    Args:
        candidate1 (callable): the first reward function candidate
        candidate2 (callable): the second reward function candidate
        grounded_op (Union[str, fs.action.PlainOperator]): the grounded operator that the reward shaping function is for. 
        init_obs_with_semantics (dict): the initial observation with semantics to use for checking the reward shaping function candidates

    Returns:
        dict[str, bool]: a dictionary whose keys are the subgoals/effects and values are booleans indicating whether the reward shaping for that subgoal/effect is duplicate in the two candidates
    """
    # check if the rw_type is not linear velocity based reward shaping, if so, raise NotImplementedError (since we only implemented the duplicate checking for linear velocity based reward shaping)
    if rw_type != 'pos_linear_vel':
        raise NotImplementedError("Duplicate checking is only implemented for linear velocity based reward shaping")
    
    duplicate_subgoals = {}
    effects = remove_duplicate_effects(grounded_op)
    for effect in effects:
        duplicate_subgoals[effect.pddl_repr()] = check_subgoal_duplicate(
            effect,
            candidate1,
            candidate2,
            init_obs_with_semantics,
        )
    return duplicate_subgoals

def prompt_llm_for_different_reward_shaping_fn_candidate(grounded_op:Union[str, fs.action.PlainOperator], obs_with_semantics:dict, existing_candidates:List[str]=[], rw_type:str='pos_linear_vel') -> str:
    """Prompt the LLM to generate different reward shaping function candidates for the grounded operator

    Args:
        grounded_op (Union[str, fs.action.PlainOperator]): the grounded operator
        obs_with_semantics (dict): the observation dictionary with semantics
        existing_candidates (List[str]): the list of existing reward shaping function candidates for the grounded operator to compare with and generate a different candidate from
        rw_type (str): the type of the reward shaping function to generate. Either exponential or linear
    Returns:
        str: the reward shaping function candidate
    """
    # check if the existing candidates are empty, if so, just prompt the LLM for a reward shaping function candidate
    if not existing_candidates:
        return prompt_llm_for_reward_shaping_fn_candidate(grounded_op, obs_with_semantics, prompt=linear_vel_reward_shaping_prompt if rw_type=='pos_linear_vel' else exponential_vel_reward_shaping_prompt)
    
    # if there are existing candidates, append the existing candidates to the prompt and ask the LLM to generate a different candidate from the existing ones
    # format the existing candidates to be included in the prompt
    existing_candidates_str = "\n\n".join([f"Reward shaping function candidate {i+1}:\n{candidate}" for i, candidate in enumerate(existing_candidates)])
    # prompt is the reward shaping function generation prompt + the different candidate prompt
    prompt = f"{exponential_vel_reward_shaping_prompt if rw_type=='pos_exp_vel' else linear_vel_reward_shaping_prompt}\n\n{different_candidate_prompt.format(existing_candidates_str=existing_candidates_str)}"
    return prompt_llm_for_reward_shaping_fn_candidate(grounded_op, obs_with_semantics, prompt=prompt)


def prompt_llm_for_reward_shaping_fn_candidate(grounded_op:Union[str, fs.action.PlainOperator], obs_with_semantics:dict,prompt:str=linear_vel_reward_shaping_prompt) -> str:
    """Prompt the LLM to generate reward shaping functions candidates for the grounded operator
    Args:
        grounded_op (str): the grounded operator
        obs_with_semantics (dict): the observation dictionary with semantics
        prompt (str): the prompt template to use for generating the reward shaping function candidate. The prompt should have placeholders for the grounded operator and the observation with semantics. If None, a default prompt will be used.
    Returns
        str: the reward shaping function candidate
    """
    if isinstance(grounded_op, fs.action.PlainOperator):
        grounded_op_repr = grounded_operator_repr(grounded_op)
        # keep only the keys that include the parameters of the grounded operator
    else:
        grounded_op_repr = grounded_op
    observation_with_semantics = filter_observation(obs_with_semantics, grounded_op)
    # if observation_with_semantics has 'gripper1_aperture', drop it
    if 'gripper1_aperture' in observation_with_semantics:
        observation_with_semantics.pop('gripper1_aperture')

    # format the prompt
    prompt = prompt.format(
        grounded_operator=grounded_op_repr,
        observation_with_semantics=observation_with_semantics
    )
    
    out = code_completion(prompt)
    #parse the output to get the reward shaping function
    fn_start = out.find('# llm generated reward shaping function')
    fn_end = out.find('```', fn_start)
    fn = out[fn_start:fn_end]
    return fn

def get_observation_with_semantics(env:MujocoEnv) -> dict:
    """Get the observation with semantics from the environment

    Args:
        env (MujocoEnv): the environment

    Returns:
        dict: the observation with semantics
    """
    return env.viewer._get_observations() if env.viewer_get_obs else env._get_observations() # detect objects' state using the observation

def choose_grounded_op(config:dict, domain:str) -> fs.Action:
    """Prompt the user to choose a grounded operator from a list of grounded operators
    Args:
        plan (List[fs.Action]): the list of grounded operators
    Returns:
        fs.Action: the chosen grounded operator
    """
    print("Choose a learnable grounded operator:")
    plan = load_plan(config['planning'][domain])
    for i, grounded_op in enumerate(plan):
        if check_executor_exists(config, domain, grounded_op):
            print(f"{i}: {grounded_op.name} executor already exists")
        else:
            print(f"{i}: {grounded_op.name}")
    choice = int(input("Enter the number of the ground operator: "))
    return plan[choice]

def check_executor_exists(config:dict, domain:str, grounded_op:fs.Action) -> bool:
    """Check if the executor exists in the grounded operator

    Args:
        config (dict): the configuration dictionary
        domain (str): the domain
        grounded_op (fs.Action): the grounded operator

    Returns:
        bool: True if the executor exists, False otherwise
    """
    executor = load_executor(config, domain, grounded_op)
    if executor is None:
        return False
    return True

def grounded_operator_repr(grounded_op:fs.Action) -> str:
    """Return a string representation of the grounded operator

    Args:
        grounded_op (fs.Action): the grounded operator
    Returns:
        str: the string representation of the grounded operator
    """
    effects:list = [eff.pddl_repr() for eff in grounded_op.effects]
    if check_duplicate_grasp_effects(grounded_op):
        effects.remove('not (free gripper1)')
    elif check_duplicate_free_gripper_effects(grounded_op):
        effects.remove('free gripper1')
    effects_str:str = ' '.join(f'({eff})' for eff in effects)
    return f"{grounded_op.name}\nprecondition: {grounded_op.precondition.pddl_repr()}\neffects: and {effects_str}"

def filter_observation(obs_with_semantics:dict, grounded_op:Union[fs.Action, str]) -> dict:
    """Filter the observation to include only the parameters of the grounded operator

    Args:
        obs_with_semantics (dict): the observation dictionary with semantics
        grounded_op (fs.Action): the grounded operator

    Returns:
        dict: the filtered observation dictionary
    """
    if isinstance(grounded_op, (fs.action.PlainOperator, fs.Action)):
        # keep only the keys that include the parameters of the grounded operator
        _, grounded_params = extract_name_params_from_grounded(grounded_op.ident())
    else:
        _, grounded_params = extract_name_params_from_grounded(grounded_op)
    observation_with_semantics = {"gripper1_pos": obs_with_semantics["gripper1_pos"], "gripper1_aperture": obs_with_semantics["gripper1_aperture"]}
    grounded_params.remove('gripper1')
    observation_with_semantics.update({k:v for k,v in obs_with_semantics.items() if any(param in k for param in grounded_params)})
    return observation_with_semantics

def find_prev_operators_executors(config:dict, domain:str, grounded_op:fs.Action) -> Dict[fs.Action, Executor]:
    """Find the executors of the previous operators in the plan

    Args:
        config (dict): the configuration dictionary
        domain (str): the domain
        grounded_op (fs.Action): the grounded operator

    Returns:
        Dict[fs.Action, Executor]: a dictionary of the previous operators and their executors
    """
    plan = load_plan(config['planning'][domain])
    prev_operators_executors:Dict[fs.Action, Executor] = OrderedDict()
    for operator in plan:
        if operator == grounded_op:
            break
        executor = load_executor(config, domain, operator)
        if executor is not None:
            prev_operators_executors[operator] = executor
        else:
            raise ValueError(f"Executor for operator {operator.name} not found")
    return prev_operators_executors

def find_subgoal_idx(grounded_op:fs.Action, subgoal:fs.SingleEffect) -> int:
    """Find the index of the subgoal in the grounded operator's effects

    Args:
        grounded_op (fs.Action): the grounded operator
        subgoal (fs.SingleEffect): the subgoal to find

    Returns:
        int: the index of the subgoal in the grounded operator's effects
    """
    effects = remove_duplicate_effects(grounded_op)
    for i, effect in enumerate(effects):
        if effect.pddl_repr() == subgoal.pddl_repr():
            return i
    raise ValueError(f"Subgoal {subgoal} not found in the grounded operator's effects: {effects}")


def remove_duplicate_effects(grounded_op:fs.Action) -> List[fs.SingleEffect]:
    """Returns a copy of the effects of the grounded op without the duplicate grasp or ungrasp effects

    Args:
        grounded_op (fs.Action): the grounded operator

    Returns:
        
    """
    effects = copy.deepcopy(grounded_op.effects)
    if check_duplicate_grasp_effects(grounded_op):
        for effect in effects:
            if effect.pddl_repr() == 'not (free gripper1)':
                effects.remove(effect)
                break
    elif check_duplicate_free_gripper_effects(grounded_op):
        for effect in effects:
            if effect.pddl_repr() == 'free gripper1':
                effects.remove(effect)
                break
    return effects

